apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-docker
        image: asia-south2-docker.pkg.dev/sde-2023/sde-a2-docker-registry/mini-portfolio:test # Replace with your custom image name
        ports:
        - containerPort: 80
